#ifndef CH585_DEMO_BOARD_H
#define CH585_DEMO_BOARD_H

#include <stdbool.h>
#include <stdint.h>

#include <chip_gpio.h>
#include <chip_i2c.h>
#include <chip_spi.h>
#include <chip_uart.h>

#ifndef DEMO_SYSTEM_CLOCK_HZ
#define DEMO_SYSTEM_CLOCK_HZ UINT32_C(62400000)
#endif

#ifndef DEMO_LED_PIN
#define DEMO_LED_PIN CHIP_PIN(CHIP_GPIO_PORT_B, 8)
#endif

#ifndef DEMO_LED_ACTIVE_HIGH
#define DEMO_LED_ACTIVE_HIGH true
#endif

#ifndef DEMO_BUTTON_PIN
#define DEMO_BUTTON_PIN CHIP_PIN(CHIP_GPIO_PORT_A, 8)
#endif

#ifndef DEMO_UART_INSTANCE
#define DEMO_UART_INSTANCE CHIP_UART_0
#endif

#ifndef DEMO_UART_BAUD_RATE
#define DEMO_UART_BAUD_RATE UINT32_C(115200)
#endif

/* UART0 default route: TX=PB7, RX=PB4. */
#ifndef DEMO_UART_TX_PIN
#define DEMO_UART_TX_PIN CHIP_PIN(CHIP_GPIO_PORT_B, 7)
#endif

#ifndef DEMO_UART_RX_PIN
#define DEMO_UART_RX_PIN CHIP_PIN(CHIP_GPIO_PORT_B, 4)
#endif

/* I2C default route: SCL=PB13, SDA=PB12. External pull-ups are recommended. */
#ifndef DEMO_I2C_INSTANCE
#define DEMO_I2C_INSTANCE CHIP_I2C_0
#endif

#ifndef DEMO_I2C_SCL_PIN
#define DEMO_I2C_SCL_PIN CHIP_PIN(CHIP_GPIO_PORT_B, 13)
#endif

#ifndef DEMO_I2C_SDA_PIN
#define DEMO_I2C_SDA_PIN CHIP_PIN(CHIP_GPIO_PORT_B, 12)
#endif

/* SPI1 route used by the demo board: CS=PA3, SCK=PA0, MOSI=PA1, MISO=PA2. */
#ifndef DEMO_SPI_FLASH_INSTANCE
#define DEMO_SPI_FLASH_INSTANCE CHIP_SPI_1
#endif

#ifndef DEMO_SPI_FLASH_CS_PIN
#define DEMO_SPI_FLASH_CS_PIN CHIP_PIN(CHIP_GPIO_PORT_A, 3)
#endif

#ifndef DEMO_SPI_FLASH_SCK_PIN
#define DEMO_SPI_FLASH_SCK_PIN CHIP_PIN(CHIP_GPIO_PORT_A, 0)
#endif

#ifndef DEMO_SPI_FLASH_MOSI_PIN
#define DEMO_SPI_FLASH_MOSI_PIN CHIP_PIN(CHIP_GPIO_PORT_A, 1)
#endif

#ifndef DEMO_SPI_FLASH_MISO_PIN
#define DEMO_SPI_FLASH_MISO_PIN CHIP_PIN(CHIP_GPIO_PORT_A, 2)
#endif

#ifndef DEMO_SPI_FLASH_CLOCK_HZ
#define DEMO_SPI_FLASH_CLOCK_HZ UINT32_C(8000000)
#endif

#ifndef DEMO_SPI_FLASH_CAPACITY_BYTES
#define DEMO_SPI_FLASH_CAPACITY_BYTES \
    (UINT32_C(2) * UINT32_C(1024) * UINT32_C(1024))
#endif

#ifndef DEMO_SPI_FLASH_PAGE_SIZE
#define DEMO_SPI_FLASH_PAGE_SIZE UINT32_C(256)
#endif

#ifndef DEMO_SPI_FLASH_SECTOR_SIZE
#define DEMO_SPI_FLASH_SECTOR_SIZE UINT32_C(4096)
#endif

#ifndef DEMO_SPI_FLASH_ENABLE_WRITE_TEST
#define DEMO_SPI_FLASH_ENABLE_WRITE_TEST 1
#endif

#ifndef DEMO_SPI_FLASH_TEST_ADDRESS
#define DEMO_SPI_FLASH_TEST_ADDRESS \
    (DEMO_SPI_FLASH_CAPACITY_BYTES - DEMO_SPI_FLASH_SECTOR_SIZE)
#endif

#ifndef DEMO_SPI_FLASH_TRANSFER_TIMEOUT_US
#define DEMO_SPI_FLASH_TRANSFER_TIMEOUT_US UINT32_C(100000)
#endif

#ifndef DEMO_SPI_FLASH_PROGRAM_TIMEOUT_US
#define DEMO_SPI_FLASH_PROGRAM_TIMEOUT_US UINT32_C(1000000)
#endif

#ifndef DEMO_SPI_FLASH_ERASE_TIMEOUT_US
#define DEMO_SPI_FLASH_ERASE_TIMEOUT_US UINT32_C(3000000)
#endif

#ifndef DEMO_SPI_FLASH_CHIP_ERASE_TIMEOUT_US
#define DEMO_SPI_FLASH_CHIP_ERASE_TIMEOUT_US UINT32_C(200000000)
#endif

#ifndef DEMO_LITTLEFS_OFFSET_BYTES
#define DEMO_LITTLEFS_OFFSET_BYTES UINT32_C(0)
#endif

#ifndef DEMO_LITTLEFS_SIZE_BYTES
#define DEMO_LITTLEFS_SIZE_BYTES \
    (DEMO_SPI_FLASH_CAPACITY_BYTES - DEMO_LITTLEFS_OFFSET_BYTES)
#endif

#ifndef DEMO_FATFS_OFFSET_BYTES
#define DEMO_FATFS_OFFSET_BYTES UINT32_C(0)
#endif

#ifndef DEMO_FATFS_SIZE_BYTES
#define DEMO_FATFS_SIZE_BYTES \
    (DEMO_SPI_FLASH_CAPACITY_BYTES - DEMO_FATFS_OFFSET_BYTES)
#endif

#endif
