set(CH585_DEMO_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")

include(common/demo.cmake)

add_subdirectory(blinky)
add_subdirectory(uart_echo)
add_subdirectory(gpio_irq)
add_subdirectory(i2c_scan)
add_subdirectory(usb_hid)
add_subdirectory(tinyusb_hid)
add_subdirectory(json_parse)
add_subdirectory(lua)
add_subdirectory(lua_usb_fatfs)
add_subdirectory(spi_flash)
add_subdirectory(spi_flash_littlefs)
add_subdirectory(spi_flash_fatfs)
add_subdirectory(ble_peripheral)
add_subdirectory(freertos_tasks)
add_subdirectory(freertos_usb_ble)
